server:
  port: 18090

spring.application.name: mate-backend
spring.servlet.multipart:
  max-file-size: 100MB
  max-request-size: 100MB

spring.datasource:
  url: jdbc:postgresql://localhost:5432/mate
  username: mateadmin
  password: mateadmin
  driver-class-name: org.postgresql.Driver

spring.jpa:
  generate-ddl: true
  properties:
    hibernate:
      order_inserts: true
      order_updates: true
      jdbc.batch_size: 2
  show-sql: true
#  database-platform: org.hibernate.dialect.PostgreSQLDialect

application.minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
