server:
  port: 18090

spring.application.name: mate-backend
spring.servlet.multipart:
  max-file-size: 100MB
  max-request-size: 100MB

spring.datasource:
  url: jdbc:postgresql://localhost:5432/mate
  username: mateadmin
  password: mateadmin
  driver-class-name: org.postgresql.Driver

spring.jpa:
  generate-ddl: true
  properties:
    hibernate:
      order_inserts: true
      order_updates: true
      jdbc.batch_size: 2
  show-sql: true
#  database-platform: org.hibernate.dialect.PostgreSQLDialect

application.minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin

spring.security.oauth2.resourceserver:
  opaquetoken:
    client-id: 288514167424483330@mate
    client-secret: PYPaSAMKGyurEqryrzoOzoZnKEbZjJRghjWU3QwBnY7X8H6YjDhwf3upe8gjTmIS
    introspection-uri: http://localhost:8080/oauth/v2/introspect
springdoc:
  swagger-ui:
    oauth:
      client-secret: pV0Kih3pb4LufBjESxUVSADleNH6epYt2lSyXTLczS8a0EOqWUsD3D6DbB42Y3B1
      client-id: 288516062696243202@mate
      authorization-url: http://localhost:8080/oauth/v2/authorize
      token-url: http://localhost:8080/oauth/v2/token
