version: '3.8'

services:
  #  mysql:
  #    restart: unless-stopped
  #    image: mysql
  #    container_name: mysql
  #    environment:
  #      - MYSQL_ROOT_PASSWORD=MyNewPass4!
  #    ports:
  #      - '3306:3306'
  #    volumes:
  #      - "./mysql/data:/var/lib/mysql:rw"
  #    healthcheck:
  #      # mysqladmin -uroot -p123  ping -h127.0.0.1
  #      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
  #      #      test: [ "CMD", "mysqladmin","-u","root","-p","123" ,"ping", "-h", "127.0.0.1" ]
  #      timeout: 45s
  #      interval: 10s
  #      retries: 10

  zitadel:
    restart: 'always'
    image: 'ghcr.io/zitadel/zitadel:latest'
    container_name: zitadel
    command: 'start-from-init --config /zitadel-config.yaml --config /zitadel-secrets.yaml --steps /zitadel-init-steps.yaml --masterkey "Jacies0AePuboo2ecaeD0ahzi9ZooF1e" --tlsMode disabled'
    depends_on:
      db:
        condition: 'service_healthy'
    ports:
      - '8080:8080'
    volumes:
      - "./zitadel/zitadel-config.yaml:/zitadel-config.yaml:ro"
      - "./zitadel/zitadel-secrets.yaml:/zitadel-secrets.yaml:ro"
      - "./zitadel/zitadel-init-steps.yaml:/zitadel-init-steps.yaml:ro"


  db:
    restart: 'always'
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - 5432:5432
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data:rw"
  minio:
    restart: 'always'
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_SERVER_CONSOLE=on
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./minio/data:/data"
      - "./minio/config:/root/.minio/"
    command: minio server --console-address ":9001" /data
