# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/setup/steps.yaml
FirstInstance:
  DefaultLanguage: zh
  Org:
    Human:
      # use the loginname root@zitadel.localhost
      Username: 'root'
      Password: 'MyNewPass4!'
      PasswordChangeRequired: false
      PreferredLanguage: zh
